vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("autocmd InsertEnter * :set norelativenumber")
vim.cmd("autocmd InsertLeave * :set relativenumber")
-- vim.cmd("source " .. vim.fn.stdpath("config") .. "\\vim\\plugins\\surround.vim")
-- vim.cmd("set cmdheight=0")
vim.cmd("set noshowmode")
vim.cmd([[
call camelcasemotion#CreateMotionMappings('<leader>')
]])
