general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  # startup_commands: ['shell-exec %HOMEPATH%/.glzr/scripts/shellexec.exe  powershell %HOMEPATH%/.glzr/start.ps1']
  startup_commands: []

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: []
  # shutdown_commands:
  # [
  #   "shell-exec %HOMEPATH%/.glzr/scripts/shellexec.exe  powershell %HOMEPATH%/.glzr/exit.ps1",
  # ]

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  show_all_in_taskbar: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

gaps:
  # Gap between adjacent windows.
  inner_gap: "6px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "6px"
    right: "6px"
    bottom: "6px"
    left: "6px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    hide_title_bar:
      enabled: false
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: false
      color: "#b4befe"

  # Visual effects to apply to non-focused windows.
  other_windows:
    hide_title_bar:
      enabled: false
    border:
      enabled: false
      color: "#585b70"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: false

      # Whether to show floating windows as always on top.
      shown_on_top: true

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a maximize button, then it'll be fullscreen'ed normally instead.
      maximized: true

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }

  - commands: ["set-floating"]
    match:
      - window_process: { regex: "SnippingTool" }
      - window_title: { regex: "Task Manager" }
      - window_title: { regex: "Run" }
      - window_process: { equals: "Spotify" }
      - window_process: { equals: "Discord" }
      - window_process: { equals: "Photos" }
      - window_title: { regex: "WhatsApp" }
      # - window_process: { equals: "Flow.Launcher" }
      #   window_title: { equals: "Settings" }
      # - window_process: { regex: "OneNote" }
      # - window_title: { regex: "Microsoft OneNote" }
      # - window_title: { regex: "Sticky Notes" }

binding_modes:
  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["lwin+tab"]

keybindings:
  - commands: ["resize --width -1%"]
    bindings: ["lwin+alt+h"]
  - commands: ["resize --width +1%"]
    bindings: ["lwin+alt+l"]
  - commands: ["resize --height +1%"]
    bindings: ["lwin+alt+k"]
  - commands: ["resize --height -1%"]
    bindings: ["lwin+alt+j"]

  - commands: ["focus --direction left"]
    bindings: ["lwin+h"]
    # https://superuser.com/a/1096597 to disable the default lwin+l shortcut in windows
  - commands: ["focus --direction right"]
    bindings: ["lwin+l"]
  - commands: ["focus --direction up"]
    bindings: ["lwin+k"]
  - commands: ["focus --direction down"]
    bindings: ["lwin+j"]

  - commands: ["move --direction left"]
    bindings: ["lwin+ctrl+h"]
  - commands: ["move --direction right"]
    bindings: ["lwin+ctrl+l"]
  - commands: ["move --direction up"]
    bindings: ["lwin+ctrl+k"]
  - commands: ["move --direction down"]
    bindings: ["lwin+ctrl+j"]
  - commands: ["focus --workspace 1"]
    bindings: ["lwin+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["lwin+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["lwin+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["lwin+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["lwin+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["lwin+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["lwin+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["lwin+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["lwin+9"]
  - commands: ["focus --next-workspace"]
    bindings: ["lwin+n"]
  - commands: ["focus --prev-workspace"]
    bindings: ["lwin+p"]

  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["lwin+ctrl+alt+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["lwin+ctrl+alt+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["lwin+ctrl+alt+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["lwin+ctrl+alt+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["lwin+ctrl+alt+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["lwin+ctrl+alt+7"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["lwin+ctrl+alt+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["lwin+ctrl+alt+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["lwin+ctrl+alt+9"]
  - commands: ["move --next-workspace", "focus --next-workspace"]
    bindings: ["lwin+ctrl+alt+n"]
  - commands: ["move --prev-workspace", "focus --prev-workspace"]
    bindings: ["lwin+ctrl+alt+p"]

  - commands: ["move-workspace --direction left"]
    bindings: ["lwin+ctrl+shift+h"]
  - commands: ["move-workspace --direction right"]
    bindings: ["lwin+ctrl+shift+l"]
  - commands: ["move-workspace --direction up"]
    bindings: ["lwin+ctrl+shift+k"]
  - commands: ["move-workspace --direction down"]
    bindings: ["lwin+ctrl+shift+j"]

  - commands: ["move --workspace 1"]
    bindings: ["lwin+ctrl+1"]
  - commands: ["move --workspace 2"]
    bindings: ["lwin+ctrl+2"]
  - commands: ["move --workspace 3"]
    bindings: ["lwin+ctrl+3"]
  - commands: ["move --workspace 4"]
    bindings: ["lwin+ctrl+4"]
  - commands: ["move --workspace 5"]
    bindings: ["lwin+ctrl+5"]
  - commands: ["move --workspace 6"]
    bindings: ["lwin+ctrl+7"]
  - commands: ["move --workspace 7"]
    bindings: ["lwin+ctrl+7"]
  - commands: ["move --workspace 8"]
    bindings: ["lwin+ctrl+8"]
  - commands: ["move --workspace 9"]
    bindings: ["lwin+ctrl+9"]
  - commands: ["move --next-workspace"]
    bindings: ["lwin+ctrl+n"]
  - commands: ["move --prev-workspace"]
    bindings: ["lwin+ctrl+p"]

  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["lwin+tab"]

  - commands: ["toggle-tiling-direction"]
    bindings: ["lwin+s"]
  - commands: ["toggle-floating"]
    bindings: ["lwin+o"]
  - commands: ["toggle-tiling"]
    bindings: ["lwin+t"]
  - commands: ["toggle-minimized"]
    bindings: ["lwin+m"]
  - commands: ["toggle-fullscreen"]
    bindings: ["lwin+f"]

  - commands: ["close"]
    bindings: ["lwin+shift+q"]
  - commands: ["wm-redraw"]
    bindings: ["lwin+r"]
  - commands: ["wm-exit"]
    bindings: ["lwin+escape"]
