gui:
  showCommandLog: false
  statusPanelView: "allBranchesLog"
  theme:
    activeBorderColor:
      - "#74c7ec"
      - bold
    inactiveBorderColor:
      - "#585b70"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#74c7ec"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"
  nerdFontsVersion: "3"
  showFileIcons: false
  commitHashLength: 7

git:
  paging:
    colorArg: always
    pager: delta --paging=never --side-by-side
    useConfig: true
  skipHookPrefix: WIP
  autoFetch: false
  autoRefresh: true
  fetchAll: false
  autoStageResolvedConflicts: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --oneline --decorate --date=relative  --pretty=medium
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: false
  truncateCopiedCommitHashesTo: 12

os:
  # editCommand: "nvim"
  # editCommandTemplate: '{{editor}} --server 127.0.0.1:8888 --remote-tab "{{filename}}"'
  # editPreset: "nvim"
  #   editPreset: "nvr --remote"
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
  # open: "nvim"
