require("config.lazy")
require("config.vim-options")
require("config.catppuccin")
-- require("config.telescope")
require("config.treesitter")
-- require("config.lualine")
require("config.bufferline")
-- require("config.gitsigns")
require("config.lazygit")
require("config.lsp")
-- require("config.dashboard")
-- require("config.toggleterm")
-- require("config.lint")
-- require("config.conform")
-- require("config.oil")
-- require("config.fidget")
-- require("config.ufo")
-- require("config.neoclip")
-- require("config.autopairs")
-- require("config.autotag")
-- require("config.indentblankline")
-- require("config.illuminate")
-- require("config.smartsplits")
