require("config.lazy")
require("config.vim-options")
require("config.catppuccin")
require("config.telescope")
require("config.treesitter")
-- require("config.nvim-tree")
require("config.lualine")
require("config.bufferline")
require("config.gitsigns")
require("config.lazygit")
require("config.lsp")
require("config.dashboard")
require("config.toggleterm")
require("config.lint")
require("config.conform")
require("config.oil")
require("config.fidget")
