return {
	"nvim-tree/nvim-web-devicons",
	-- This is to prevent this plugin to load on startup
	-- It will load when other plugins that depend on it are loaded, such as telescope and dashboard
	event = "InsertEnter",
	opts = {
    -- stylua: ignore start
		override_by_filename = {
			[".env.production"] =  { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },
			[".env.development"] = { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },
			[".env.preview"] =     { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },
			[".env.test"] =        { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },
			[".env.prod"] =        { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },
			[".env.dev"] =         { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },

			[".env.local"] =             { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },
			[".env.production.local"] =  { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },
			[".env.development.local"] = { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },
			[".env.preview.local"] =     { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },
			[".env.test.local"] =        { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },
			[".env.prod.local"] =        { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },
			[".env.dev.local"] =         { icon = "", color = "#FAF743", cterm_color = "227", name = "Env" },

			["docker-compose.production.yaml"] =  { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["docker-compose.development.yaml"] = { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["docker-compose.deployment.yaml"] =  { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["docker-compose.production.yml"] =   { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["docker-compose.development.yml"] =  { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["docker-compose.deployment.yml"] =   { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["docker-compose.prod.yaml"] =        { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["docker-compose.dev.yaml"] =         { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["docker-compose.deploy.yaml"] =      { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["docker-compose.prod.yml"] =         { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["docker-compose.dev.yml"] =          { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["docker-compose.deploy.yml"] =       { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },

			["compose.prodduction.yaml"] = { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["compose.development.yaml"] = { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["compose.deployment.yaml"] =  { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["compose.production.yml"] =   { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["compose.development.yml"] =  { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["compose.deployment.yml"] =   { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["compose.prod.yaml"] =        { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["compose.dev.yaml"] =         { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["compose.deploy.yaml"] =      { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["compose.prod.yml"] =         { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["compose.dev.yml"] =          { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },
			["compose.deploy.yml"] =       { icon = "󰡨", color = "#458EE6", cterm_color = "68", name = "DockerCompose" },

      [".ignore"] =       { icon = "", color = "#F54D27", cterm_color = "196", name = "Ignore"       },
      [".fdignore"] =     { icon = "", color = "#F54D27", cterm_color = "196", name = "FdIgnore"     },
      [".rgignore"] =     { icon = "", color = "#F54D27", cterm_color = "196", name = "RgIgnore"     },
      [".dockerignore"] = { icon = "󰡨", color = "#F54D27", cterm_color = "196", name = "DockerIgnore" },

      [".postcssrc"] =          { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      [".postcssrc.json"] =     { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      [".postcssrc.yaml"] =     { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      [".postcssrc.yml"] =      { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      [".postcssrc.js"] =       { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      [".postcssrc.mjs"] =      { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      [".postcssrc.cjs"] =      { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      ["postcss.config.js"] =   { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      ["postcss.config.mjs"] =  { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      ["postcss.config.cjs "] = { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      [".postcssrc.ts"] =       { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      [".postcssrc.mts"] =      { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      [".postcssrc.cts"] =      { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      ["postcss.config.ts"] =   { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      ["postcss.config.mts"] =  { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
      ["postcss.config.cts"] =  { icon = "", color = "#DD3A0A", cterm_color = "202", name = "PostCSS" },
		},
		override_by_extension = {
      ["ignore"] =       { icon = "", color = "#F54D27", cterm_color = "196", name = "Ignore"       },
      ["fdignore"] =     { icon = "", color = "#F54D27", cterm_color = "196", name = "FdIgnore"     },
      ["rgignore"] =     { icon = "", color = "#F54D27", cterm_color = "196", name = "RgIgnore"     },
      ["dockerignore"] = { icon = "󰡨", color = "#F53D27", cterm_color = "196", name = "DockerIgnore" },
    },
		-- stylua: ignore end
	},
}
